# Generated by Django 5.0.6 on 2024-07-28 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentDetails',
            fields=[
                ('assignment_number', models.IntegerField(primary_key=True, serialize=False)),
                ('unit_title', models.CharField(blank=True, max_length=50)),
                ('_class', models.CharField(max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('questions', models.TextField()),
                ('submit_by', models.CharField(blank=True, max_length=20)),
                ('unit_number', models.IntegerField(blank=True, null=True)),
                ('is_checked', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('roll_number', models.IntegerField(primary_key=True, serialize=False)),
                ('_class', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_file', models.FileField(upload_to='assignment_File/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments_manager.userdetails')),
            ],
        ),
    ]
