# Generated by Django 5.0.6 on 2024-08-02 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPannel', '0004_remove_admin_registration_assignment'),
        ('assignments_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentdetails',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='adminPannel.admin_registration'),
        ),
    ]
