# Generated by Django 5.0.6 on 2024-08-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments_manager', '0002_assignmentdetails_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmentdetails',
            name='assignment_number',
            field=models.IntegerField(),
        ),
    ]
