# Generated by Django 5.0.6 on 2024-08-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments_manager', '0003_assignmentdetails_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentdetails',
            old_name='_class',
            new_name='className',
        ),
    ]
