# Generated by Django 5.0.6 on 2024-08-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments_manager', '0004_rename__class_assignmentdetails_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentdetails',
            name='subject_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
