# Generated by Django 5.0.6 on 2024-08-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments_manager', '0005_assignmentdetails_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentdetails',
            name='semester',
            field=models.IntegerField(null=True),
        ),
    ]
