# Generated by Django 5.0.6 on 2024-08-07 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments_manager', '0006_assignmentdetails_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='userdetails',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='assignments_manager.userdetails'),
        ),
    ]
