# Generated by Django 5.0.6 on 2024-08-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments_manager', '0008_remove_usersubmission_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='semester',
            field=models.IntegerField(null=True),
        ),
    ]
