# Generated by Django 5.0.6 on 2024-08-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments_manager', '0011_remove_userdetails_is_checked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='massage',
            field=models.TextField(blank=True),
        ),
    ]
