# Generated by Django 5.0.6 on 2024-08-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments_manager', '0012_usersubmission_massage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='assignmentid',
            field=models.IntegerField(null=True),
        ),
    ]
