# Generated by Django 5.0.6 on 2024-08-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments_manager', '0013_usersubmission_assignmentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmission',
            name='is_checked',
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
