# Generated by Django 5.0.6 on 2024-08-09 12:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments_manager', '0013_usersubmission_assignmentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(2018)])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments_manager.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10)),
                ('present_days', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('attendance_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_manager.attendanceyear')),
            ],
        ),
    ]
