# Generated by Django 5.0.6 on 2024-08-09 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_admission_year_student_registration_semester'),
        ('attendance_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceyear',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student_registration'),
        ),
    ]
