# Generated by Django 5.0.6 on 2024-07-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_registration',
            name='admission_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_registration',
            name='course',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_registration',
            name='enrollment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_registration',
            name='mobile',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_registration',
            name='rollnumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
