# Generated by Django 5.0.6 on 2024-07-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_registration_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_registration',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pictures/'),
        ),
    ]
