# Generated by Django 5.0.6 on 2024-07-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_student_registration_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_registration',
            name='admission_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='course',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='enrollment',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='rollnumber',
            field=models.IntegerField(null=True),
        ),
    ]
