# Generated by Django 5.0.6 on 2024-07-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_registration_id_student_registration_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_registration',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student_registration',
            name='user',
        ),
        migrations.AlterField(
            model_name='student_registration',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
