# Generated by Django 5.0.6 on 2024-07-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_student_registration_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_registration',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student_registration',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
