# Generated by Django 5.0.6 on 2024-07-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_student_registration_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_registration',
            name='profession',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
