# Generated by Django 5.0.6 on 2024-08-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_student_registration_profession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_registration',
            old_name='admission_year',
            new_name='semester',
        ),
    ]
