# Generated by Django 5.0.6 on 2024-09-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_admission_year_student_registration_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_registration',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
