# Generated by Django 5.0.6 on 2024-07-31 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPannel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admin_registration',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='admin_registration',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='admin_registration',
            name='password',
        ),
        migrations.AddField(
            model_name='admin_registration',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
